var d=self,h=d.Nf;(function(){function a(a){c?c.push(a):setTimeout(a,0)}var b={version:"0.7.2.0",Rg:function(a){return void 0===a},Qg:function(a){return null===a},qa:function(a){return null===a||void 0===a},Sg:function(a){return null!==a&&void 0!==a}},c=[];d.attachEvent&&d.attachEvent("onload",function(){if(c){var a=c;c=null;for(var b=0,e=a.length;b<e;b++)a[b]()}});h||(d.Nf=h={Va:a,ready:a});for(var e in b)h[e]=b[e]})();Object.ia="Object";Object.Ja=null;Object.wg=function(a){for(var b in a)delete a[b]};
Object.be=function(a,b){return void 0!==a[b]};Object.keys?Object.Cf=function(a){return Object.keys(a).length}:(Object.keys=function(a){var b=[],c;for(c in a)b.push(c);return b},Object.Cf=function(a){var b=0,c;for(c in a)b++;return b});Boolean.ia="Boolean";Boolean.parse=function(a){return"true"==a.toLowerCase()};Number.ia="Number";Number.parse=function(a){return a&&a.length?0<=a.indexOf(".")||0<=a.indexOf("e")||a.endsWith("f")||a.endsWith("F")?parseFloat(a):parseInt(a,10):0};
Number.prototype.format=function(a){return h.qa(a)||0==a.length||"i"==a?this.toString():z(this,a,!1)};Number.prototype.de=function(a){return h.qa(a)||0==a.length||"i"==a?this.toLocaleString():z(this,a,!0)};
Number.wc=function(a,b,c,e){var f=null;c=a.indexOf(c);0<c&&(f=a.substr(c),a=a.substr(0,c));(c=a.startsWith("-"))&&(a=a.substr(1));var g=0,k=b[g];if(a.length<k)return f?a+f:a;for(var l=a.length,m="",n=!1;!n;){var p=k,w=l-p;0>w&&(k+=w,p+=w,w=0,n=!0);if(!p)break;w=a.substr(w,p);m=m.length?w+e+m:w;l-=p;g<b.length-1&&(g++,k=b[g])}c&&(m="-"+m);return f?m+f:m};
function z(a,b,c){c=c?h.je.Xf.Jf:h.je.Yf.Jf;var e="",f=-1;1<b.length&&(f=parseInt(b.substr(1)));b=b.charAt(0);switch(b){case "d":case "D":e=parseInt(Math.abs(a)).toString();-1!=f&&(e=e.length<f?String.Xd(f-e.length)+e:e);0>a&&(e="-"+e);break;case "x":case "X":e=parseInt(Math.abs(a)).toString(16);"X"==b&&(e=e.toUpperCase());-1!=f&&(e=e.length<f?String.Xd(f-e.length)+e:e);break;case "e":case "E":e=-1==f?a.toExponential():a.toExponential(f);"E"==b&&(e=e.toUpperCase());break;case "f":case "F":case "n":case "N":-1==
f&&(f=c.Tg);e=a.toFixed(f).toString();f&&"."!=c.ge&&(f=e.indexOf("."),e=e.substr(0,f)+c.ge+e.substr(f+1));if("n"==b||"N"==b)e=Number.wc(e,c.Vg,c.ge,c.Ug);break;case "c":case "C":-1==f&&(f=c.Ag);e=Math.abs(a).toFixed(f).toString();f&&"."!=c.Vd&&(f=e.indexOf("."),e=e.substr(0,f)+c.Vd+e.substr(f+1));e=Number.wc(e,c.Cg,c.Vd,c.Bg);e=0>a?String.format(c.Dg,e):String.format(c.Eg,e);break;case "p":case "P":-1==f&&(f=c.Wg),e=(100*Math.abs(a)).toFixed(f).toString(),f&&"."!=c.he&&(f=e.indexOf("."),e=e.substr(0,
f)+c.he+e.substr(f+1)),e=Number.wc(e,c.Yg,c.he,c.Xg),e=0>a?String.format(c.Zg,e):String.format(c.$g,e)}return e}String.ia="String";String.ke="";String.compare=function(a,b,c){c&&(a&&(a=a.toUpperCase()),b&&(b=b.toUpperCase()));a=a||"";b=b||"";return a==b?0:a<b?-1:1};String.concat=function(){return 2===arguments.length?arguments[0]+arguments[1]:Array.prototype.join.call(arguments,"")};
String.prototype.endsWith=function(a){return a.length?a.length>this.length?!1:this.substr(this.length-a.length)==a:!0};String.Gg=function(a,b,c){return 0==String.compare(a,b,c)};String.sd=function(a,b,c){String.td||(String.td=/(\{[^\}^\{]+\})/g);return a.replace(String.td,function(a,f){var g=b[parseInt(f.substr(1))+1];if(h.qa(g))return"";if(g.format){var k=null,l=f.indexOf(":");0<l&&(k=f.substring(l+1,f.length-1));return c?g.de(k):g.format(k)}return c?g.toLocaleString():g.toString()})};
String.format=function(a){return String.sd(a,arguments,!1)};String.Xd=function(a){for(var b="0",c=1;c<a;c++)b+="0";return b};String.Gf=function(a){return!a||!a.length};String.de=function(a){return String.sd(a,arguments,!0)};String.prototype.remove=function(a,b){return!b||a+b>this.length?this.substr(0,a):this.substr(0,a)+this.substr(a+b)};String.prototype.startsWith=function(a){return a.length?a.length>this.length?!1:this.substr(0,a.length)==a:!0};
String.prototype.trim||(String.prototype.trim=function(){return this.replace(/\s*$/,"").replace(/^\s*/,"")});Array.ia="Array";Array.Sb=[h.Qb];Array.prototype.add=function(a){this.push(a)};Array.prototype.addRange=function(a){this.push.apply(this,a)};Array.prototype.clear=function(){this.length=0};Array.prototype.clone=function(){return 1===this.length?[this[0]]:Array.apply(null,this)};Array.prototype.contains=function(a){return 0<=this.indexOf(a)};Array.prototype.enqueue=function(a){this.qf=!0;this.push(a)};
function N(a){return a.length?a[a.qf?0:a.length-1]:null}Array.prototype.every||(Array.prototype.every=function(a,b){for(var c=this.length,e=0;e<c;e++)if(e in this&&!a.call(b,this[e],e,this))return!1;return!0});Array.prototype.filter||(Array.prototype.filter=function(a,b){for(var c=this.length,e=[],f=0;f<c;f++)if(f in this){var g=this[f];a.call(b,g,f,this)&&e.push(g)}return e});
Array.prototype.forEach||(Array.prototype.forEach=function(a,b){for(var c=this.length,e=0;e<c;e++)e in this&&a.call(b,this[e],e,this)});Array.prototype.Ua=function(){return new h.Ob(this)};Array.prototype.index=function(a,b){for(var c=this.length,e={},f=0;f<c;f++)if(f in this){var g=a.call(b,this[f],f);String.Gf(g)||(e[g]=this[f])}return e};Array.prototype.indexOf||(Array.prototype.indexOf=function(a,b){var c=this.length;if(c)for(var e=b||0;e<c;e++)if(this[e]===a)return e;return-1});
Array.prototype.map||(Array.prototype.map=function(a,b){for(var c=this.length,e=Array(c),f=0;f<c;f++)f in this&&(e[f]=a.call(b,this[f],f,this));return e});Array.parse=function(a){return eval("("+a+")")};Array.prototype.remove=function(a){a=this.indexOf(a);return 0<=a?(this.splice(a,1),!0):!1};Array.prototype.Qc=function(a){this.splice(a,1)};Array.prototype.removeRange=function(a,b){return this.splice(a,b)};
Array.prototype.some||(Array.prototype.some=function(a,b){for(var c=this.length,e=0;e<c;e++)if(e in this&&a.call(b,this[e],e,this))return!0;return!1});Array.Pf=function(a){return Array.prototype.slice.call(a)};RegExp.ia="RegExp";RegExp.parse=function(a){if(a.startsWith("/")){var b=a.lastIndexOf("/");if(1<b)return new RegExp(a.substring(1,b),a.substr(b+1))}return null};Error.ia="Error";
Error.yg=function(a,b,c){a=Error(a);if(b)for(var e in b)a[e]=b[e];c&&(a.Jg=c);if(!(h.qa(a.stack)||h.qa(a.fileName)||h.qa(a.lineNumber))){b=a.stack.split("\n");c=b[0];for(e=a.fileName+":"+a.lineNumber;!h.qa(c)&&-1===c.indexOf(e);)b.shift(),c=b[0];c=b[1];isNullOrUndefined(c)||(c=c.match(/@(.*):(\d+)$/),h.qa(c)||(b.shift(),a.stack=b.join("\n"),a.fileName=c[1],a.lineNumber=parseInt(c[2])))}return a};h.sa=d.sa||function(){};h.sa.ia="Debug";
h.sa.writeln||(h.sa.writeln=function(a){d.console?d.console.debug?d.console.debug(a):d.console.log&&d.console.log(a):d.opera&&d.opera.postError&&d.opera.postError(a)});h.sa.rd=function(a){h.sa.writeln(a);eval("debugger;")};h.sa.assert=function(a,b){a||(b="Assert failed: "+b,confirm(b+"\r\n\r\nBreak into debugger?")&&h.sa.rd(b))};h.sa.Hg=function(a){h.sa.rd(a)};d.I=Function;d.I.ia="Type";d.$c=function(a){this.ia=a};d.$c.prototype={ve:!0,getName:function(){return this.ia}};
d.I.Kf=function(){d.tc||(d.tc={});d.dd||(d.dd=[]);if(!d.tc.trn){for(var a=self,b=["trn"],c=0;c<b.length;c++){var e=b[c],f=a[e];f||(a[e]=f=new d.$c(b.slice(0,c+1).join(".")),0==c&&d.dd.add(f));a=f}d.tc.trn=a}};d.I.prototype.U=function(a,b,c){this.prototype.constructor=this;this.ia=a;this.ad=!0;this.Ja=b||Object;b&&(this.Rb=!0);if(c){this.Sb=[];for(var e=2;e<arguments.length;e++)c=arguments[e],this.Sb.add(c)}};function R(a,b){a.ia=b;a.cd=!0}
d.I.prototype.Rc=function(){if(this.Rb){var a=this.Ja;a.Rb&&a.Rc();for(var b in a.prototype){var c=a.prototype[b];this.prototype[b]||(this.prototype[b]=c)}delete this.Rb}};d.I.prototype.Lf||(d.I.prototype.Lf=d.I.prototype.Rc);function S(a,b){return h.qa(b)?!1:a==Object||b instanceof a?!0:T(a,d.I.Bf(b))}
function T(a,b){if(a==Object||a==b)return!0;if(a.ad)for(var c=b.Ja;c;){if(a==c)return!0;c=c.Ja}else if(a.cd){var e=b.Sb;if(e&&e.contains(a))return!0;for(c=b.Ja;c;){if((e=c.Sb)&&e.contains(a))return!0;c=c.Ja}}return!1}d.I.Lg=function(a){return 1==a.ad};d.I.Mg=function(a){return 1==a.ue};d.I.Ng=function(a){return 1==a.ue&&1==a.bd};d.I.Og=function(a){return 1==a.cd};d.I.Pg=function(a){return 1==a.ve};d.I.ug=function(a,b){return S(b,a)};d.I.bh=function(a,b){return S(b,a)?a:null};
d.I.Bf=function(a){var b=null;try{b=a.constructor}catch(c){}b&&b.ia||(b=Object);return b};d.I.Ef=function(a){if(!a)return null;d.I.uc||(d.I.uc={});var b=d.I.uc[a];b||(b=eval(a),d.I.uc[a]=b);return b};d.I.parse=function(a){return d.I.Ef(a)};h.rc=function(){};h.rc.U("Enum");
h.rc.parse=function(a,b){var c=a.prototype;if(a.bd){for(var e=b.split("|"),f=0,g=!0,k=e.length-1;0<=k;k--){var l=e[k].trim(),m=!1;for(n in c)if(n===l){f|=c[n];m=!0;break}if(!m){g=!1;break}}if(g)return f}else for(var n in c)if(n===b)return c[n];throw"Invalid Enumeration Value";};
h.rc.eg=function(a){var b=this.prototype;if(this.bd&&0!==a){var c=[];for(e in b)b[e]&a&&(c.length&&c.add(" | "),c.add(e));if(!c.length)throw"Invalid Enumeration Value";return c.join("")}for(var e in b)if(b[e]===a)return e;throw"Invalid Enumeration Value";};h.R=function(){};h.R.U("Delegate");h.R.empty=function(){};h.R.ye=function(a,b,c){for(var e=0;e<a.length;e+=2)if(a[e]===b&&a[e+1]===c)return!0;return!1};
h.R.xc=function(a){function b(){if(2==a.length)return a[1].apply(a[0],arguments);for(var c=a.clone(),b=0;b<c.length;b+=2)h.R.ye(a,c[b],c[b+1])&&c[b+1].apply(c[b],arguments);return null}b.wa=a;return b};h.R.create=function(a,b){return a?h.R.xc([a,b]):b};h.R.xg=function(a,b){return a?b?h.R.xc((a.wa?a.wa:[null,a]).concat(b.wa?b.wa:[null,b])):a.wa?a:h.R.create(null,a):b.wa?b:h.R.create(null,b)};
h.R.remove=function(a,b){if(!a||a===b)return null;if(!b)return a;var c=a.wa,e=null,f;b.wa?(e=b.wa[0],f=b.wa[1]):f=b;for(var g=0;g<c.length;g+=2)if(c[g]===e&&c[g+1]===f){if(2==c.length)return null;c.splice(g,2);return h.R.xc(c)}return a};h.R.zg=function(a,b,c){c=c||"__"+(new Date).valueOf();self[c]=b?a:function(){try{delete self[c]}catch(b){self[c]=void 0}a.apply(null,arguments)};return c};h.R.Fg=function(a){delete self[a]};h.R.vg=function(a){self[a]=h.R.empty};h.ob=function(){};
h.ob.prototype={ee:null,reset:null};h.ob.Ua=function(a){return a?a.Ua?a.Ua():new h.Ob(a):null};R(h.ob,"IEnumerator");h.Qb=function(){};h.Qb.prototype={Ua:null};R(h.Qb,"IEnumerable");h.Ob=function(a){this.ed=a;this.Ba=-1;this.current=null};h.Ob.prototype={ee:function(){this.Ba++;this.current=this.ed[this.Ba];return this.Ba<this.ed.length},reset:function(){this.Ba=-1;this.current=null}};h.Ob.U("ArrayEnumerator",null,h.ob);h.Wc=function(){};h.Wc.prototype={zf:null};R(h.Wc,"IDisposable");
h.Yc=function(a){this.Lc=h.qa(a)?[]:[a]};h.Yc.prototype={append:function(a){h.qa(a)||this.Lc.add(a);return this},clear:function(){this.Lc=[]},toString:function(a){return this.Lc.join(a||"")}};h.Yc.U("StringBuilder");h.Pb=function(){};h.Pb.U("EventArgs");h.Pb.ke=new h.Pb;d.XMLHttpRequest||(d.XMLHttpRequest=function(){for(var a=["Msxml2.XMLHTTP","Microsoft.XMLHTTP"],b=0;b<a.length;b++)try{return new ActiveXObject(a[b])}catch(c){}return null});
h.Vc=function(){var a=h.Vc;a.Rb&&a.Rc();a.Ja.apply(this);this.cancel=!1};h.Vc.U("CancelEventArgs",h.Pb);h.se=function(a,b){this.first=a;this.second=b};h.se.U("Tuple");h.ha=function(){this.Fb=null};h.ha.prototype={};h.ha.Kc=[];h.ha.hf={zf:function(){h.ha.Kc.pop()}};h.ha.ah=function(a){h.ha.Kc.push(a);return h.ha.hf};h.ha.we=function(a){var b=h.ha.Kc,c=b.length;if(c){a=a||[];for(var e=0;e<c;e++){var f=b[e];a.contains(f)||a.push(f)}return a}return null};h.ha.af=function(a){for(var b=0,c=a.length;b<c;b++)a[b].Kg()};
h.ha.U("Observable");h.Xc=function(a){this.Ca=a||[];this.Fb=null};h.Xc.prototype={add:function(a){this.Ca.push(a);U(this)},clear:function(){this.Ca.clear();U(this)},contains:function(a){return this.Ca.contains(a)},Ua:function(){this.Fb=h.ha.we(this.Fb);return this.Ca.Ua()},indexOf:function(a){return this.Ca.indexOf(a)},remove:function(a){return this.Ca.remove(a)?(U(this),!0):!1},Qc:function(a){this.Ca.Qc(a);U(this)},Pf:function(){return this.Ca}};
function U(a){var b=a.Fb;b&&(a.Fb=null,h.ha.af(b))}h.Xc.U("ObservableCollection",null,h.Qb);h.le=function(){};R(h.le,"IApplication");h.me=function(){};R(h.me,"IContainer");h.pe=function(){};R(h.pe,"IObjectFactory");h.ne=function(){};R(h.ne,"IEventManager");h.oe=function(){};R(h.oe,"IInitializable");(function(a){function b(a,b,f,g,k,l){this.Ia=16;this.re=288;this.status=0;this.root=null;this.ya=0;var m=Array(this.Ia+1),n,y,x,u,q,t,J,K=Array(this.Ia+1),G,F,C,B=new c,O=Array(this.Ia);u=Array(this.re);var D,L=Array(this.Ia+1),P,M,Q;Q=this.root=null;for(q=0;q<m.length;q++)m[q]=0;for(q=0;q<K.length;q++)K[q]=0;for(q=0;q<O.length;q++)O[q]=null;for(q=0;q<u.length;q++)u[q]=0;for(q=0;q<L.length;q++)L[q]=0;n=256<b?a[256]:this.Ia;G=a;F=0;q=b;do m[G[F]]++,F++;while(0<--q);if(m[0]==b)this.root=null,this.status=
this.ya=0;else{for(t=1;t<=this.Ia&&0==m[t];t++);J=t;l<t&&(l=t);for(q=this.Ia;0!=q&&0==m[q];q--);x=q;l>q&&(l=q);for(P=1<<t;t<q;t++,P<<=1)if(0>(P-=m[t])){this.status=2;this.ya=l;return}if(0>(P-=m[q]))this.status=2,this.ya=l;else{m[q]+=P;L[1]=t=0;G=m;F=1;for(C=2;0<--q;)L[C++]=t+=G[F++];G=a;q=F=0;do 0!=(t=G[F++])&&(u[L[t]++]=q);while(++q<b);b=L[x];L[0]=q=0;G=u;F=0;u=-1;D=K[0]=0;C=null;for(M=0;J<=x;J++)for(a=m[J];0<a--;){for(;J>D+K[1+u];){D+=K[1+u];u++;M=(M=x-D)>l?l:M;if((y=1<<(t=J-D))>a+1)for(y-=a+1,
C=J;++t<M&&!((y<<=1)<=m[++C]);)y-=m[C];D+t>n&&D<n&&(t=n-D);M=1<<t;K[1+u]=t;C=Array(M);for(y=0;y<M;y++)C[y]=new c;Q=null==Q?this.root=new e:Q.next=new e;Q.next=null;Q.list=C;O[u]=C;0<u&&(L[u]=q,B.pa=K[u],B.e=16+t,B.t=C,t=(q&(1<<D)-1)>>D-K[u],O[u-1][t].e=B.e,O[u-1][t].pa=B.pa,O[u-1][t].n=B.n,O[u-1][t].t=B.t)}B.pa=J-D;F>=b?B.e=99:G[F]<f?(B.e=256>G[F]?16:15,B.n=G[F++]):(B.e=k[G[F]-f],B.n=g[G[F++]-f]);y=1<<J-D;for(t=q>>D;t<M;t+=y)C[t].e=B.e,C[t].pa=B.pa,C[t].n=B.n,C[t].t=B.t;for(t=1<<J-1;0!=(q&t);t>>=
1)q^=t;for(q^=t;(q&(1<<D)-1)!=L[u];)D-=K[u],u--}this.ya=K[1];this.status=0!=P&&1!=x?1:0}}}function c(){this.n=this.pa=this.e=0;this.t=null}function e(){this.list=this.next=null}var f=[0,1,3,7,15,31,63,127,255,511,1023,2047,4095,8191,16383,32767,65535],g=[3,4,5,6,7,8,9,10,11,13,15,17,19,23,27,31,35,43,51,59,67,83,99,115,131,163,195,227,258,0,0],k=[0,0,0,0,0,0,0,0,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5,0,99,99],l=[1,2,3,4,5,7,9,13,17,25,33,49,65,97,129,193,257,385,513,769,1025,1537,2049,3073,4097,
6145,8193,12289,16385,24577],m=[0,0,0,0,1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,11,11,12,12,13,13],n=[16,17,18,0,8,7,9,6,10,5,11,4,12,3,13,2,14,1,15];a.Za||(a.Za={});a.Za.sc=function(a){this.Vf();this.pc=a;this.qc=0};a.Za.sc.prototype={Yd:function(a){for(var c,b=Array(1024),e=[],f=0;f<a&&0<(c=this.Uf(b,0,b.length));)e[e.length]=String.fromCharCode.apply(null,b.slice(0,c)),f+=c;return f?(this.pc=this.pc.slice(this.qc),this.qc=0,e.join("")):""},Qf:function(){return this.pc.length==this.qc?-1:this.pc.charCodeAt(this.qc++)&
255},M:function(a){for(;this.Wa<a;)this.nb|=this.Qf()<<this.Wa,this.Wa+=8},P:function(a){return this.nb&f[a]},L:function(a){this.nb>>=a;this.Wa-=a},oc:function(a,c,b){var e,f,g;if(0==b)return 0;for(g=0;;){this.M(this.ra);f=this.Ha.list[this.P(this.ra)];for(e=f.e;16<e;){if(99==e)return-1;this.L(f.pa);e-=16;this.M(e);f=f.t[this.P(e)];e=f.e}this.L(f.pa);if(16==e)this.aa&=32767,a[c+g++]=this.Ga[this.aa++]=f.n;else{if(15==e)break;this.M(e);this.ga=f.n+this.P(e);this.L(e);this.M(this.mb);f=this.ie.list[this.P(this.mb)];
for(e=f.e;16<e;){if(99==e)return-1;this.L(f.pa);e-=16;this.M(e);f=f.t[this.P(e)];e=f.e}this.L(f.pa);this.M(e);this.Xa=this.aa-f.n-this.P(e);for(this.L(e);0<this.ga&&g<b;)this.ga--,this.Xa&=32767,this.aa&=32767,a[c+g++]=this.Ga[this.aa++]=this.Ga[this.Xa++]}if(g==b)return b}this.Fa=-1;return g},Wf:function(a,c,b){var e;e=this.Wa&7;this.L(e);this.M(16);e=this.P(16);this.L(16);this.M(16);if(e!=(~this.nb&65535))return-1;this.L(16);this.ga=e;for(e=0;0<this.ga&&e<b;)this.ga--,this.aa&=32767,this.M(8),a[c+
e++]=this.Ga[this.aa++]=this.P(8),this.L(8);0==this.ga&&(this.Fa=-1);return e},Tf:function(a,c,e){if(null==this.nc){var f,n=Array(288);for(f=0;144>f;f++)n[f]=8;for(;256>f;f++)n[f]=9;for(;280>f;f++)n[f]=7;for(;288>f;f++)n[f]=8;this.Uc=7;f=new b(n,288,257,g,k,this.Uc);if(0!=f.status)return alert("HufBuild error: "+f.status),-1;this.nc=f.root;this.Uc=f.ya;for(f=0;30>f;f++)n[f]=5;this.Tc=5;f=new b(n,30,0,l,m,this.Tc);if(1<f.status)return this.nc=null,alert("HufBuild error: "+f.status),-1;this.Rf=f.root;
this.Tc=f.ya}this.Ha=this.nc;this.ie=this.Rf;this.ra=this.Uc;this.mb=this.Tc;return this.oc(a,c,e)},Sf:function(a,c,e){var f,r,H,A,I,y,x,u=Array(316);for(f=0;f<u.length;f++)u[f]=0;this.M(5);y=257+this.P(5);this.L(5);this.M(5);x=1+this.P(5);this.L(5);this.M(4);f=4+this.P(4);this.L(4);if(286<y||30<x)return-1;for(r=0;r<f;r++)this.M(3),u[n[r]]=this.P(3),this.L(3);for(;19>r;r++)u[n[r]]=0;this.ra=7;r=new b(u,19,19,null,null,this.ra);if(0!=r.status)return-1;this.Ha=r.root;this.ra=r.ya;A=y+x;for(f=H=0;f<
A;)if(this.M(this.ra),I=this.Ha.list[this.P(this.ra)],r=I.pa,this.L(r),r=I.n,16>r)u[f++]=H=r;else if(16==r){this.M(2);r=3+this.P(2);this.L(2);if(f+r>A)return-1;for(;0<r--;)u[f++]=H}else{17==r?(this.M(3),r=3+this.P(3),this.L(3)):(this.M(7),r=11+this.P(7),this.L(7));if(f+r>A)return-1;for(;0<r--;)u[f++]=0;H=0}this.ra=9;r=new b(u,y,257,g,k,this.ra);0==this.ra&&(r.status=1);if(0!=r.status)return-1;this.Ha=r.root;this.ra=r.ya;for(f=0;f<x;f++)u[f]=u[f+y];this.mb=6;r=new b(u,x,0,l,m,this.mb);this.ie=r.root;
this.mb=r.ya;return 0==this.mb&&257<y||0!=r.status?-1:this.oc(a,c,e)},Vf:function(){null==this.Ga&&(this.Ga=Array(65536));this.Wa=this.nb=this.aa=0;this.Fa=-1;this.mc=!1;this.ga=this.Xa=0;this.nc=this.Ha=null},Uf:function(a,c,b){var e,f;for(e=0;e<b&&(!this.mc||-1!=this.Fa);){if(0<this.ga){if(0!=this.Fa)for(;0<this.ga&&e<b;)this.ga--,this.Xa&=32767,this.aa&=32767,a[c+e++]=this.Ga[this.aa++]=this.Ga[this.Xa++];else{for(;0<this.ga&&e<b;)this.ga--,this.aa&=32767,this.M(8),a[c+e++]=this.Ga[this.aa++]=
this.P(8),this.L(8);0==this.ga&&(this.Fa=-1)}if(e==b)break}if(-1==this.Fa){if(this.mc)break;this.M(1);0!=this.P(1)&&(this.mc=!0);this.L(1);this.M(2);this.Fa=this.P(2);this.L(2);this.Ha=null;this.ga=0}switch(this.Fa){case 0:f=this.Wf(a,c+e,b-e);break;case 1:f=null!=this.Ha?this.oc(a,c+e,b-e):this.Tf(a,c+e,b-e);break;case 2:f=null!=this.Ha?this.oc(a,c+e,b-e):this.Sf(a,c+e,b-e);break;default:f=-1}if(-1==f)return this.mc?0:-1;e+=f}return e}};a.Za.ae=function(c){return(new a.Za.sc(c)).Yd(4E9)}})(self);(function(a){function b(a){this.depth=this.index=0;this.H=a;this.location={start:0,jc:1,kc:1,end:a.length,empty:!0};this.Mb=[this.location];this.Pc=!1;"?"===this.H.charAt(1)&&this.$d();this.location.empty=!1}b.prototype={advance:function(){this.Ea=null;this.$d();var a=this.location.start;++a;this.location.empty=!1;if("/"!==this.H.charAt(a))return this.location.empty="/"===this.H.charAt(this.H.indexOf(">",a)-1),!0;this.location.end=!0;return!1},yf:function(a){if(a)return a.split("&quot;").join('"').split("&lt;").join("<").split("&gt;").join(">").split("&amp;").join("&")},
ce:function(){var a=this.location.start+1,b=this.H.indexOf(">",a);this.location.empty&&--b;a=this.H.substring(a,b);this.Ea={};b=a.indexOf(" ");if(-1!==b){this.Wd=a.substring(0,b);for(var a=a.slice(b),a=a.split('"'),b=a.length-1,f=0;f<b;++f){var g=a[f],k=a[++f];this.Ea[g.substring(1,g.length-1)]=k}}else this.Wd=a},$d:function(){if(this.Pc)this.Pc=!1,this.location.start=this.H.indexOf("<",this.location.start+1);else{var a=this.location.jc;if(!this.location.empty)for(var b=this.location.kc;0<b;)a=this.H.indexOf("<",
a),"/"===this.H.charAt(++a)?--b:(a=this.H.indexOf(">",a),"/"!==this.H.charAt(a-1)&&++b);this.location.start=this.H.indexOf("<",a)}this.location.jc=this.location.start+1;this.location.kc=1},mark:function(){this.H.mark&&this.H.mark(this.location.start)},J:function(){null!==this.Ea&&"undefined"!==typeof this.Ea||this.ce();return this.Wd},G:function(){++this.depth;this.location={start:this.location.start};this.Mb[this.Mb.length]=this.location;this.Pc=!0},F:function(){--this.depth;this.Ea=null;var a=this.location.jc,
b=this.location.kc,f=this.location.empty,g=this.location.end;this.Mb.pop();this.location=this.Mb[this.Mb.length-1];this.location.jc=a;this.location.kc=g?0:f?b:b+1},O:function(){return this.location.empty?!0:"/"===this.H.charAt(this.H.indexOf("<",this.location.start+1)+1)},w:function(a){null!==this.Ea&&"undefined"!==typeof this.Ea||this.ce();return this.yf(this.Ea[a])}};a.te=b})(self);self.I.Kf();
d.trn.a=function(a,b,c){this.done=!1;this.Gd=1E4;this.Pa={};this.Sa=this.Eb=0;this.K=[];this.ac=[];this.la=[];this.la.add({});this.Cb=0;this.c=a;this.Kd=this.Nb("Width");this.Jd=this.Nb("Height");this.K.push(d.trn.Ma.Ff(this.Kd,this.Jd));this.$="c."+d.trn.a.f[d.trn.a.Re]+"();";this.va="c."+d.trn.a.f[d.trn.a.Qe]+"();";this.da=!1;this.Fc=b;this.xb=c;this.bf=-1<navigator.userAgent.indexOf("Android")&&-1===navigator.userAgent.indexOf("Chrome")&&-1===navigator.userAgent.indexOf("Firefox");this.b="";this.c.G();
this.c.advance();a=this.c.J();d.trn.a.i(a,"FixedPage.Resources")&&(this.c.G(),this.c.advance(),this.Qd(),this.c.F());this.Oa=!1};d.trn.a.i=function(a,b){var c=d.trn.a.xf;return a===b?!0:a===c+b};d.trn.a.l=function(a){return d.trn.a.Ib(a,3)};d.trn.a.Jb=function(a){return a.split("\\").join("\\\\").split('"').join('\\"')};d.trn.a.Ib=function(a,b){var c=b,e=Math.abs(a);.5>e&&(c=5E-4>e?5E-7>e?b+6:b+4:b+2);c=Math.pow(10,c);a=Math.round(a*c)/c;return a.toString()};
d.trn.a.v=function(a,b){if(!a)throw Error(b);};d.trn.a.Ig=function(a){return(new d.trn.a(a,!1)).Ve()};
d.trn.a.prototype={vd:function(a){return a+"."+d.trn.a.f[d.trn.a.qd]+"(t.m_a,t.m_b,t.m_c,t.m_d,t.m_h,t.m_v);"},ze:function(a,b){var c="ox"+this.Ta;this.b+="var "+b+"=document.createElement('canvas');";this.b+=b+".width=b[2]";this.b+=";"+b+".height=b[3]";this.b+=";";this.b+="var "+c+"="+b+".getContext('2d');";var e="o"+this.Ta;this.b+="var "+e+"=function(c,ob){";this.b+="c."+d.trn.a.f[d.trn.a.hd]+"();";this.b+="c."+d.trn.a.f[d.trn.a.zc]+"(0,0);";this.b+="c."+d.trn.a.f[d.trn.a.rb]+"(b[2],0);";this.b+=
"c."+d.trn.a.f[d.trn.a.rb]+"(b[2],b[3]);";this.b+="c."+d.trn.a.f[d.trn.a.rb]+"(0,b[3]);";this.b+="c."+d.trn.a.f[d.trn.a.jd]+"();";this.b+="c."+d.trn.a.f[d.trn.a.Vb]+"(-b[0],-b[1]);";this.b+=this.vd("c");var f=this.eb(),g=this.c.w("RenderTransform");if(null!=g){var k=new d.trn.D;k.V(g);f.Ka(k)}this.b+=f.tb();this.b+=a;this.b+="};";this.b+=e+"("+c+",b);";return c},Ye:function(a){var b="t"+this.Ta;this.b+=this.Dd("var "+b+"=function(c,ob)");var c="tx"+this.Ta;this.b+=a+".width=b[2];";this.b+=a+".height=b[3];";
this.b+="var "+c+"="+a+".getContext('2d');";a=this.eb();this.b+=c+"."+d.trn.a.f[d.trn.a.Vb]+"(-b[0],-b[1]);";this.b+=this.vd(c);this.b+=a.zd(c);this.b+=b+"("+c+",b);";return c},yc:function(a,b){var c,e=this.Ue(),f=this.c.J();d.trn.a.i(f,"Path")?c=this.Dc():d.trn.a.i(f,"Canvas")?c=this.Wb():d.trn.a.i(f,"Glyphs")?c=this.Cc():(c=null,d.trn.a.v(!1,"Invalid Element "+f));c.lb(e);c.Hf()?(++this.Ta,e="tc"+this.Ta,this.b+="var b=["+d.trn.a.l(c.o)+","+d.trn.a.l(c.s)+","+d.trn.a.l(c.o+c.B)+","+d.trn.a.l(c.s+
c.A)+"];",this.b+="var x1c=ob[0];var y1c=ob[1];var x2c=x1c+c.canvas.width;var y2c=y1c+c.canvas.height;",this.b+="var x1=b[0]*t.m_a + b[1]*t.m_c + t.m_h;",this.b+="var y1=b[0]*t.m_b + b[1]*t.m_d + t.m_v;",this.b+="var x2=b[2]*t.m_a + b[3]*t.m_c + t.m_h;",this.b+="var y2=b[2]*t.m_b + b[3]*t.m_d + t.m_v;",this.b+="if(x1<x2){if(x1<x1c){x1=x1c}if(x2>x2c){x2=x2c}b[0]=Math.floor(x1);b[2]=Math.ceil(x2-x1);}",this.b+="else{if(x2<x1c){x2=x1c}if(x1>x2c){x1=x2c}b[2]=Math.ceil(x1-x2);b[0]=Math.floor(x2);}",this.b+=
"if(y1<y2){if(y1<y1c){y1=y1c}if(y2>y2c){y2=y2c}b[1]=Math.floor(y1);b[3]=Math.ceil(y2-y1);}",this.b+="else{if(y2<y1c){y2=y1c}if(y1>y2c){y1=y2c}b[3]=Math.ceil(y1-y2);b[1]=Math.floor(y2);}",this.b+="if(b[2]>0 && b[3]>0){",this.b+="var "+e+"=document.createElement('canvas');",c=this.Ye(e),a&&(c="oc"+this.Ta,f=this.ze(a,c),this.b+=f+"."+d.trn.a.f[d.trn.a.ld]+"='source-in';",this.b+=f+"."+d.trn.a.f[d.trn.a.od]+"(1,0,0,1,0,0);",this.b+=f+"."+d.trn.a.f[d.trn.a.qb]+"("+e+",0,0);",e=c,c=f),"source-over"===
b||this.xb?(this.b+=this.$,this.Oc(b),this.b+="c."+d.trn.a.f[d.trn.a.od]+"(1,0,0,1,b[0]-ob[0],b[1]-ob[1]);",this.b+="c."+d.trn.a.f[d.trn.a.qb]+"("+e+",0,0);",this.b+=this.va):this.b+=c+"."+d.trn.a.f[d.trn.a.Ce]+'(c,"'+b+'",{"x":b[0]-ob[0],"y":b[1]-ob[1]});',this.b+="}",this.Ld=!0):this.da=!1},Wb:function(){var a=new d.trn.ba;this.T();var b=this.c.w("RenderTransform");if(null!=b){var c=new d.trn.D;c.V(b);this.S(c)}b=this.c.w("Clip");null!=b&&(a=this.Aa(b));b=null;if(!this.c.O()){for(this.c.G();this.c.advance();)c=
this.c.J(),d.trn.a.i(c,"Canvas.Clip")?(d.trn.a.v(!this.c.O(),"Canvas.Clip: Must contain PathGeometry element"),this.c.G(),this.c.advance()&&(c=new d.trn.D,c.V(this.u("Transform")),this.S(c),a.lb(this.Aa(this.u("Figures"))),c=c.vb(),this.S(c)),this.c.F()):d.trn.a.i(c,"Path")?null!=b?b.Sc(this.Dc()):b=this.Dc():d.trn.a.i(c,"Glyphs")?null!=b?b.Sc(this.Cc()):b=this.Cc():d.trn.a.i(c,"Canvas")&&(null!=b?b.Sc(this.Wb()):b=this.Wb());this.c.F()}null!=b&&a.lb(b);this.ma();return a},lf:function(){var a=this.za("trn:BlendMode",
"source-over"),a=this.da?"source-over":a,b=this.Mc();b||(this.b+=this.$,this.T());var c=null,e=this.c.w("OpacityMask");null!=e&&(c=this.cb(e,!0,"c."+d.trn.a.f[d.trn.a.ab]+"();"));if(!this.c.O()){for(this.c.G();this.c.advance();)if(e=this.c.J(),d.trn.a.i(e,"Canvas.Resources"))this.c.O()?d.trn.a.v(!1,"Canvas.Resources must contain ResourceDictionary element"):(this.c.G(),this.c.advance(),this.Qd(),this.c.F());else if(d.trn.a.i(e,"Canvas.Clip"))d.trn.a.v(!this.c.O(),"Canvas.Clip: Must contain PathGeometry element"),
this.c.G(),this.c.advance()&&(b||(this.b+=this.$,b=!0,this.T()),e=new d.trn.D,e.V(this.u("Transform")),this.b+=this.S(e),d.trn.a.v(d.trn.a.i(this.c.J(),"PathGeometry"),"Path.Clip must contain PathGeometry"),this.hc(this.u("Figures")),e=e.vb(),this.b+=this.S(e)),this.c.F();else if(d.trn.a.i(e,"Canvas.OpacityMask"))this.da||(this.c.G(),this.c.advance(),c=this.bb("c."+d.trn.a.f[d.trn.a.ta],"c."+d.trn.a.f[d.trn.a.ab]+"();"),this.c.F());else if(d.trn.a.i(e,"Path")||d.trn.a.i(e,"Glyphs")||d.trn.a.i(e,"Canvas")||
d.trn.a.i(e,"trn:Glyphs")){if(null!=c||"source-over"!==a){this.Gb();this.c.F();this.da=!0;this.yc(c,a);return}this.Oa=!1;break}this.Oa&&this.c.F()}this.Oa&&this.Gb();this.da=!1},Gb:function(){this.b+=this.va;this.ma()},Nb:function(a){a=this.c.w(a);d.trn.a.v(null!=a,this.c.J()+": "+a+" is not defined");return parseFloat(a)},xa:function(a,b){a=this.c.w(a);return null!=a?parseFloat(a):b},u:function(a){a=this.c.w(a);d.trn.a.v(null!=a,this.c.J()+": "+a+" is not defined");return a},za:function(a,b){a=this.c.w(a);
return null!=a?a:b},Zd:function(){var a;a=this.c.w("x:Key");d.trn.a.v(null!=a,"Key must be defined for elements in a resource dictionary");return a},Mc:function(){0===this.Sa&&this.c.mark();var a=!1,b=this.xa("Opacity",1);1>b&&(a||(a=!0,this.b+=this.$,this.T()),this.b+=this.$a(b));b=this.c.w("RenderTransform");null!=b&&(a||(a=!0,this.b+=this.$,this.T()),this.Na(b)?this.b+=this.Yb(b):this.Od(b));b=this.c.w("Clip");null!=b&&(a||(this.b+=this.$,this.T()),this.hc(b),a=!0);return a},hc:function(a){var b=
!0;a&&"F"===a[0]&&(b=!1);this.Rd(b?"evenodd":"nonzero");this.$e(this.Aa(a));this.Nc(a);this.b+="c."+d.trn.a.f[d.trn.a.De]+"("+(b?"'evenodd'":"")+");"},kf:function(a){var b=[];for(a=h.ob.Ua(a.split(";"));a.ee();){var c=a.current,e=new d.trn.Ba,c=c.split(",");if(1<=c.length){if(0<c[0].length){var f=c[0].split(")");if(2<=f.length){var g=f[0].substr(1).split(":");e.bc=parseInt(g[0]);e.Gc=parseInt(g[1])}e.ec=parseInt(f[f.length-1]);e.Db=!0}2<=c.length&&(0<c[1].length&&(e.Ec=parseFloat(c[1]),e.Ic=!0),3<=
c.length&&(0<c[2].length&&(e.fc=parseFloat(c[2])),4<=c.length&&0<c[3].length&&(e.gc=parseFloat(c[3]))))}b.add(e)}return b},Ze:function(){var a=this.u("UnicodeString"),b="",c=0,e,f,g;for(2<=a.length&&"{"===a.charAt(0)&&"}"===a.charAt(1)&&(a=a.substr(2));c<a.length;)e=a.charCodeAt(c),9==e?(b+=String.fromCharCode(10),c++):128>e?(b+=String.fromCharCode(e),c++):191<e&&224>e?(f=a.charCodeAt(c+1),b+=String.fromCharCode((e&31)<<6|f&63),c+=2):(f=a.charCodeAt(c+1),g=a.charCodeAt(c+2),b+=String.fromCharCode((e&
15)<<12|(f&63)<<6|g&63),c+=3);return b},Cc:function(){var a=new d.trn.ba,b=this.c.w("Clip");null!=b&&(a=this.Aa(b));return a},Bc:function(a,b){return this.bf&&1===a.length?b[d.trn.a.Je]+'("'+(a+" "):b[d.trn.a.Ie]+'("'+a},Zc:function(a){return 0===Object.keys(a).length&&a.constructor===Object},Nd:function(a,b){var c=this.za("trn:BlendMode","source-over"),c=this.da?"source-over":c,e="source-over"!=c&&!this.xb,f=this.Mc();this.xb&&this.Oc(c);var g=this.Nb("OriginX"),k=this.Nb("OriginY"),l=this.u("FontUri");
this.yb[l]=null;var m=this.Nb("FontRenderingEmSize"),n=this.kf(this.za("Indices",""));if(200>m){m/=200;f||(this.T(),this.b+=this.$,f=!0);var p=new d.trn.D;p.ub(m,0,0,m,g,k);m=200;g=k=0;this.b+=p.tb()}for(var p=0,w="p"+ ++this.cf,g="var "+w+"="+g+";",v=this.Ze(),E=0,r=0,H=m/100,A="",I={},y=0;y<n.length;++y){var x=n[y];if(E!==x.fc||r!==x.gc)A&&(g+="c."+this.Bc(d.trn.a.Jb(A),a)+'",'+w+(E?"+"+d.trn.a.l(E*H):"")+","+d.trn.a.l(k-r*H)+");",g+=w+"+=c."+a[d.trn.a.nd]+'("'+d.trn.a.Jb(A)+'").'+a[d.trn.a.Se]+
";"),E=x.fc,r=x.gc,A="";x.Db&&(I[A.length]=v.substr(p,x.bc));x.Ic?(this.Zc(I)||(g+="c."+a[d.trn.a.pd]+"("+JSON.stringify(I)+");"),g+="c."+this.Bc(d.trn.a.Jb(A+(x.Db?String.fromCharCode(x.ec+57344):v.substr(p,1))),a)+'",'+w+(E?"+"+d.trn.a.l(E*H):"")+","+d.trn.a.l(k-r*H)+");",g+=w+"+=",A&&(g+="c."+a[d.trn.a.nd]+'("'+d.trn.a.Jb(A)+'").width+'),g+=d.trn.a.l(x.Ec*H)+";",I={},A=""):A+=x.Db?String.fromCharCode(x.ec+57344):v.substr(p,1);y+=x.Gc-1;p+=x.bc}if(A||p<v.length)this.Zc(I)||(g+="c."+a[d.trn.a.pd]+
"("+JSON.stringify(I)+");"),g+="c."+this.Bc(d.trn.a.Jb(A+v.substr(p,v.length-p)),a)+'",'+w+","+d.trn.a.l(k)+");";n=k=null;p=this.c.w("OpacityMask");null!=p&&(n=this.cb(p,!0,"c."+a[d.trn.a.ab]+"();"));if(!this.c.O()&&!b){for(this.c.G();this.c.advance();)p=this.c.J(),d.trn.a.i(p,"Glyphs.Clip")?(d.trn.a.v(!this.c.O(),"Canvas.Clip: Must contain PathGeometry element"),this.c.G(),this.c.advance()&&(f||(f=!0,this.b+=this.$,this.T()),p=new d.trn.D,p.V(this.u("Transform")),this.b+=p.tb(),d.trn.a.v(d.trn.a.i(this.c.J(),
"PathGeometry"),"Path.Clip must contain PathGeometry"),w=this.u("Figures"),this.hc(w),p=p.vb(),this.b+=p.tb()),this.c.F()):d.trn.a.i(p,"Glyphs.Fill")?(this.c.G(),this.c.advance(),k=this.bb("c."+a[d.trn.a.ta],g),this.c.F()):d.trn.a.i(p,"Glyphs.OpacityMask")&&!this.da&&(this.c.G(),this.c.advance(),n=this.bb("c."+a[d.trn.a.ta],"c."+a[d.trn.a.ab]+"();"),this.c.F());this.c.F()}if(null==n||e)"otf"===l.substr(l.indexOf(".")+1)?(l=l.substr(0,l.length-4),l=parseInt(l.substr(7))):l=parseInt(l.substr(35,8),
16),l="f"+l,Object.be(this.Pa,l)?10>this.Pa[l].length&&(this.Pa[l]+=v.substr(0,10-this.Pa[l].length)):this.Pa[l]=v.substr(0,10),this.rf(d.trn.a.l(m)+"px "+l),p=this.c.w("Fill"),null!=p&&(k=this.Na(p)?this.cb(p,!0,g):this.Zb(p,"c."+a[d.trn.a.ta],g)),null!=k&&(-1===k.indexOf(this.$)?this.ic(k,g):this.ic("c."+a[d.trn.a.ta]+"='#000000';"+g,g));f&&(this.b+=this.va,this.ma());if(null!=n||e)this.da=!0,this.yc(n,c);this.da=!1},wd:function(){var a=new String;this.c.G();d.trn.a.v(this.c.advance(),"Gradient brushes must contain GradientStops");
for(this.c.G();this.c.advance();)var b=this.u("Color"),c=this.u("Offset"),a=a+("g."+d.trn.a.f[d.trn.a.Ae]+"("+c+","+this.ud(b)+");");this.c.F();this.c.F();return a},yd:function(a,b,c){var e=this.c.w("Transform"),f=new String,f=f+this.$;this.T();null!=e&&(c.V(e),f+=this.S(c));c=this.xa("Opacity",1);1>c&&(f+=this.$a(c));c=this.u("StartPoint");e=this.u("EndPoint");f+="var g=c."+d.trn.a.f[d.trn.a.Ee]+"("+c+","+e+");";f+=this.wd();f=f+(a+"=g;")+b+this.va;this.ma();return f},Ad:function(a,b,c){var e=this.c.w("Transform"),
f=new String,g=this.u("RadiusX"),k=this.u("RadiusY"),l=this.u("GradientOrigin"),m=this.u("Center"),f=f+this.$;this.T();if(null!=e||g!==k)null!=e&&c.V(e),g!==k&&(e=parseFloat(g),k=parseFloat(k),d.trn.a.v(0<e&&0<k,"Invalid radius value"),k/=e,e=new d.trn.D,e.ub(1,0,0,k,0,0),c.Ka(e),m=m.split(","),m=d.trn.a.l(parseFloat(m[0]))+","+d.trn.a.l(parseFloat(m[1])/k),l=l.split(","),l=d.trn.a.l(parseFloat(l[0]))+","+d.trn.a.l(parseFloat(l[1])/k)),f+=this.S(c);c=this.xa("Opacity",1);1>c&&(f+=this.$a(c));f+="var g=c."+
d.trn.a.f[d.trn.a.Fe]+"("+l+",0,"+m+","+g+");";f+=this.wd();f=f+(a+"=g;")+b+this.va;this.ma();return f},wf:function(){d.trn.a.v(!this.dc,"Incorrect custom glyph start");this.b+="c."+d.trn.a.f[d.trn.a.Ge]+"();";this.dc=!0},Te:function(){d.trn.a.v(this.dc,"Incorrect custom glyph end");this.b+="c."+d.trn.a.f[d.trn.a.He]+"();";this.dc=!1},vf:function(a){var b=N(this.K);a!==b.kb?(a.startsWith("c."+d.trn.a.f[d.trn.a.Ub]+"='")&&(b.kb=a),this.b+=a):this.b+="c."+d.trn.a.f[d.trn.a.sb]+"();"},ic:function(a,
b){var c=N(this.K);a!==c.gb?(a.startsWith("c."+d.trn.a.f[d.trn.a.ta]+"='")&&(c.gb=a),this.b+=a):this.b+=b},Oc:function(a){var b=N(this.K);a!==b.Bb&&(b.Bb=a,this.b+="c."+d.trn.a.f[d.trn.a.ld]+'="',this.b+=a,this.b+='";')},$a:function(a){var b=N(this.K);b.Qa*=a;a=""+("c."+d.trn.a.f[d.trn.a.Le]+"=");a+=d.trn.a.l(b.Qa);return a+";"},Rd:function(a){var b=N(this.K);a!==b.fb&&(b.fb=a)},Sd:function(a){var b=N(this.K);a!==b.ib&&(b.ib=a,this.b+="c."+d.trn.a.f[d.trn.a.md]+"=",this.b+=d.trn.a.l(a),this.b+=";")},
sf:function(a){var b=N(this.K);a!==b.hb&&(b.hb=a,this.b+="c."+d.trn.a.f[d.trn.a.Me]+"='",this.b+=a,this.b+="';")},tf:function(a){var b=N(this.K);a!==b.Ra&&(b.Ra=a,this.b+="c."+d.trn.a.f[d.trn.a.Ne]+"='",this.b+=a,this.b+="';")},uf:function(a){var b=N(this.K);a!==b.jb&&(b.jb=a,this.b+="c."+d.trn.a.f[d.trn.a.Oe]+"=",this.b+=d.trn.a.l(a),this.b+=";")},rf:function(a){var b=N(this.K);a!==b.Ab&&(b.Ra=a,this.b+="c."+d.trn.a.f[d.trn.a.Ke]+"='",this.b+=a,this.b+="';")},S:function(a){N(this.K).ua.Ka(a);return a.tb()},
eb:function(){return N(this.K).ua},Ue:function(){return N(this.K).na},$e:function(a){N(this.K).na.lb(a)},T:function(a){a=a?N(this.K).If():N(this.K).clone();this.K.push(a);this.la.add({})},ma:function(){this.K.pop();this.la.Qc(this.la.length-1)},xd:function(a,b,c){var e="",f=this.c.w("Transform"),e=e+this.$;this.T();var g=this.u("Viewbox"),k=new d.trn.ba;k.Va(g);var g=this.u("Viewport"),l=new d.trn.ba;l.Va(g);if(null!=f||k!==l){var g=l.B/k.B,m=l.A/k.A,n=l.o-k.o*g,k=l.s-k.s*m;null!=f&&(this.Na(f)?e+=
this.Yb(f):c.V(f));f=new d.trn.D;f.ub(g,0,0,m,n,k);c.Ka(f);e+=this.S(c)}c=this.xa("Opacity",1);1>c&&(e+=this.$a(c));c=this.za("TileMode","None");f=this.u("ImageSource");this.yb[f]=null;e=e+a+("=c."+d.trn.a.f[d.trn.a.kd]+"(window.ci."+("i"+parseInt(f.split("/")[2]))+",");e=("None"===c?e+"'no-repeat'":e+"'repeat'")+");";e+=b;e+=this.va;this.ma();return e},We:function(){var a="",b=this.c.w("Transform"),a=a+this.$;this.T();var c=this.u("Viewbox"),e=new d.trn.ba;e.Va(c);var c=this.u("Viewport"),f=new d.trn.ba;
f.Va(c);if(null!=b||e!==f){var c=f.B/e.B,g=f.A/e.A,k=f.o-e.o*c,e=f.s-e.s*g,f=new d.trn.D;null!=b&&(this.Na(b)?a+=this.Yb(b):f.V(b));b=new d.trn.D;b.ub(c,0,0,g,k,e);f.Ka(b);a+=this.S(f)}b=this.xa("Opacity",1);1>b&&(a+=this.$a(b));this.za("TileMode","None");b=this.u("ImageSource");this.yb[b]=null;b="i"+parseInt(b.split("/")[2]);this.Fc?(a=a+("var img=window.ci."+b+";")+("var a=asc(t)*"+this.eb().Kb()+";"),a+="var st=Math.log(1/a)*"+this.Fc+";",a=a+'var sc=1;for(var i=1; i<st; ++i){var can=document.createElement("canvas");can.width = img.width * 0.5;can.height = img.height * 0.5;'+
('can.getContext("2d").'+d.trn.a.f[d.trn.a.qb]+"(img, 0, 0, can.width, can.height);"),a=a+"img=can;sc*=2;}"+("c."+d.trn.a.f[d.trn.a.Ac]+"(sc,sc);"),a+="c."+d.trn.a.f[d.trn.a.qb]+"(img, 0, 0);"):a+="c."+d.trn.a.f[d.trn.a.qb]+"(window.ci."+b+", 0, 0);";a+=this.va;this.ma();return a},nf:function(){this.Od(this.c.w("Matrix"))},Od:function(a){if(null!=a){var b=new d.trn.D;b.V(a);this.b+=this.S(b)}},j:function(a){for(var b=new String;","!==a.C.charAt(a.m)&&" "!==a.C.charAt(a.m)&&"\x00"!==a.C.charAt(a.m)&&
("E"===a.C.charAt(a.m)||"e"===a.C.charAt(a.m)||!("A"<=a.C.charAt(a.m)&&"Z">=a.C.charAt(a.m)||"a"<=a.C.charAt(a.m)&&"z">=a.C.charAt(a.m)));)b+=a.C.charAt(a.m),++a.m;for(;" "===a.C.charAt(a.m)||","===a.C.charAt(a.m);)++a.m;return parseFloat(b)},Aa:function(a){var b=" ",c=new d.trn.Tb(a,0,null,0),e=new d.trn.ba,f=!0;e.Lb(0,0,0,0);if(c.m<c.C.length)for(;" "===c.C.charAt(c.m);)c.m++;for(;c.m<a.length;){if("A"<=c.C.charAt(c.m)&&"Z">=c.C.charAt(c.m)||"a"<=c.C.charAt(c.m)&&"z">=c.C.charAt(c.m))b=c.C.charAt(c.m),
c.m++;else{var g,k;"a">b&&("H"!==b&&(c.h=0),"V"!==b&&(c.g=0));switch(b){case "m":case "M":c.g+=this.j(c);c.h+=this.j(c);f?(e.Lb(c.g,c.h,c.g,c.h),f=!1):e.fa(c.g,c.h);c.N=!1;break;case "l":case "L":c.g+=this.j(c);c.h+=this.j(c);e.fa(c.g,c.h);c.N=!1;break;case "c":case "C":g=this.j(c)+c.g;k=this.j(c)+c.h;e.fa(g,k);c.N=!0;c.ja=this.j(c)+c.g;c.ka=this.j(c)+c.h;e.fa(c.ja,c.ka);c.g+=this.j(c);c.h+=this.j(c);e.fa(c.g,c.h);break;case "q":case "Q":g=this.j(c)+c.g;k=this.j(c)+c.h;e.fa(g,k);c.g+=this.j(c);c.h+=
this.j(c);e.fa(c.g,c.h);c.N=!1;break;case "s":case "S":c.N||(c.ja=c.g,c.ka=c.h);g=2*c.g-c.ja;k=2*c.h-c.ka;e.fa(g,k);c.N=!0;c.ja=this.j(c)+c.g;c.ka=this.j(c)+c.h;e.fa(c.ja,c.ka);c.g+=this.j(c);c.h+=this.j(c);e.fa(c.g,c.h);break;case "h":case "H":c.g+=this.j(c);e.fa(c.g,c.h);c.N=!1;break;case "v":case "V":c.h+=this.j(c);e.fa(c.g,c.h);c.N=!1;break;default:this.j(c),c.N=!1}}for(;" "===a.charAt(c.m);)++c.m}return e.Df(this.eb())},Dc:function(){var a=null;this.T();var b=this.c.w("RenderTransform");if(null!=
b){var c=new d.trn.D;c.V(b);this.S(c)}var e=this.c.w("Stroke"),f=this.xa("StrokeThickness",1),b=this.c.w("Clip");null!=b&&(a=this.Aa(b));b=this.c.w("Data");if(!this.c.O()){for(this.c.G();this.c.advance();)if(c=this.c.J(),d.trn.a.i(c,"Path.Data")&&!this.c.O()){this.c.G();this.c.advance()&&(c=new d.trn.D,c.V(this.u("Transform")),this.S(c),d.trn.a.v(d.trn.a.i(this.c.J(),"PathGeometry"),"Path.Data must contain PathGeometry"),b=this.u("Figures"));this.c.F();break}else d.trn.a.i(c,"Path.Clip")?(d.trn.a.v(!this.c.O(),
"Path.Clip: Must contain PathGeometry element"),this.c.G(),this.c.advance()&&(c=new d.trn.D,c.V(this.u("Transform")),this.S(c),a=this.Aa(this.u("Figures")),c=c.vb(),this.S(c)),this.c.F()):d.trn.a.i(c,"Path.Stroke")&&(e=!0);this.c.F()}null!=a?a.lb(this.Aa(b)):a=this.Aa(b);this.ma();e&&a.ae(f);return a},wb:function(a,b,c){a.N=!1;if(null==a.oa)this.b+="c."+d.trn.a.f[d.trn.a.rb]+"("+d.trn.a.l(a.g)+","+d.trn.a.l(a.h)+");";else for(var e=a.oa.length,f=a.g-b,g=a.h-c,k=g/f,l=Math.sqrt(f*f+g*g);1E-10<l;){var m=
a.oa[a.cc%e]-a.zb,n=m>l;n&&(a.zb+=l,m=l);if(f){var p=Math.sqrt(m*m/(1+k*k));0>f&&(p=-p);b+=p;c+=k*p}else c+=0<g?m:-m;this.b+="c."+(a.cc%2?d.trn.a.f[d.trn.a.zc]:d.trn.a.f[d.trn.a.rb])+"("+d.trn.a.l(b)+","+d.trn.a.l(c)+");";l-=m;n||(++a.cc,a.zb=0)}},gd:function(a,b,c,e,f){a.N=!0;if(null==a.oa)this.b+="c."+d.trn.a.f[d.trn.a.Be]+"("+d.trn.a.l(e)+","+d.trn.a.l(f)+","+d.trn.a.l(a.ja)+","+d.trn.a.l(a.ka)+","+d.trn.a.l(a.g)+","+d.trn.a.l(a.h)+");";else{var g=this.eb().Kb(),g=(Math.abs(a.g-b)+Math.abs(a.h-
c))/5*g,k=a.g,l=a.h;a.g=b;a.h=c;for(var g=1/parseInt(g),m=0;1>=m;m+=g){var n=1-m,p=a.g,w=a.h;a.g=n*n*n*b+3*n*n*m*e+3*n*m*m*a.ja+m*m*m*k;a.h=n*n*n*c+3*n*n*m*f+3*n*m*m*a.ka+m*m*m*l;this.wb(a,p,w)}}},xe:function(a){if(null==a.oa)this.b+="c."+d.trn.a.f[d.trn.a.jd]+"();";else{var b=a.g,c=a.h;a.g=a.Hd;a.h=a.Id;this.wb(a,b,c)}},gf:function(a){a.Hd=a.g;a.Id=a.h;this.b+="c."+d.trn.a.f[d.trn.a.zc]+"("+d.trn.a.l(a.g)+","+d.trn.a.l(a.h)+");";a.N=!1;a.cc=a.Hc;a.zb=a.Da},mf:function(a,b){var c,e,f=a.g,g=a.h;"a">
b&&("H"!==b&&(a.h=0),"V"!==b&&(a.g=0));switch(b){case "m":case "M":a.g+=this.j(a);a.h+=this.j(a);this.gf(a);break;case "l":case "L":a.g+=this.j(a);a.h+=this.j(a);this.wb(a,f,g);break;case "c":case "C":c=this.j(a)+a.g;e=this.j(a)+a.h;a.ja=this.j(a)+a.g;a.ka=this.j(a)+a.h;a.g+=this.j(a);a.h+=this.j(a);this.gd(a,f,g,c,e);break;case "q":case "Q":c=this.j(a)+a.g;e=this.j(a)+a.h;a.g+=this.j(a);a.h+=this.j(a);this.b+="c."+d.trn.a.f[d.trn.a.Pe]+"("+d.trn.a.l(c)+","+d.trn.a.l(e)+","+d.trn.a.l(a.g)+","+d.trn.a.l(a.h)+
");";a.N=!1;break;case "s":case "S":a.N||(a.ja=a.g,a.ka=a.h);c=2*a.g-a.ja;e=2*a.h-a.ka;a.N=!0;a.ja=this.j(a)+a.g;a.ka=this.j(a)+a.h;a.g+=this.j(a);a.h+=this.j(a);this.gd(a,f,g,c,e);break;case "h":case "H":a.g+=this.j(a);this.wb(a,f,g);a.N=!1;break;case "v":case "V":a.h+=this.j(a);this.wb(a,f,g);a.N=!1;break;default:this.j(a),a.N=!1}},Xe:function(a){if("Flat"===a)return"butt";if("Square"===a)return"square";if("Round"===a||"Triangle"===a)return"round";d.trn.a.v(!1,"Invalid line cap "+a);return""},Nc:function(a){this.Pd(a,
null,0)},Pd:function(a,b,c){var e=" ";b=new d.trn.Tb(a,0,b,c);this.b+="c."+d.trn.a.f[d.trn.a.hd]+"();";if(b.m<b.C.length)for(;" "===b.C.charAt(b.m);)b.m++;for(;b.m<a.length;)for("A"<=b.C.charAt(b.m)&&"Z">=b.C.charAt(b.m)||"a"<=b.C.charAt(b.m)&&"z">=b.C.charAt(b.m)?(e=b.C.charAt(b.m),"z"!==b.C.charAt(b.m)&&"Z"!==b.C.charAt(b.m)||this.xe(b),b.m++):this.mf(b,e);" "===a.charAt(b.m);)++b.m},pf:function(){var a=this.za("trn:BlendMode","source-over"),a=this.da?"source-over":a,b="source-over"!=a&&!this.xb,
c=this.c.w("Data"),e=!0;c&&"F"===c[0]&&(e=!1);var f="c."+d.trn.a.f[d.trn.a.ab]+"("+(e?"'evenodd'":"")+");",g=!1,k=this.Mc(),l=this.c.w("Fill");null!=l&&(l=this.Na(l)?this.cb(l,!0,f):this.Zb(l,"c."+d.trn.a.f[d.trn.a.ta],f));this.xb&&this.Oc(a);var m=null,n=this.xa("StrokeThickness",1),p=this.c.w("Stroke");null!=p&&(this.Sd(n),p=this.Na(p)?this.cb(p,!1,"c."+d.trn.a.f[d.trn.a.sb]+"();"):this.Zb(p,"c."+d.trn.a.f[d.trn.a.Ub],"c."+d.trn.a.f[d.trn.a.sb]+"();"));var w=null,v=this.c.w("OpacityMask");null!=
v&&(w=this.cb(v,!0,"c."+d.trn.a.f[d.trn.a.ab]+"();"));v=null;if(!this.c.O()){for(this.c.G();this.c.advance();){var E=this.c.J();d.trn.a.i(E,"Path.Clip")?(d.trn.a.v(!this.c.O(),"Path.Clip: Must contain PathGeometry element"),this.c.G(),this.c.advance()&&(k||(k=!0,this.b+=this.$,this.T()),v=new d.trn.D,v.V(this.u("Transform")),this.b+=this.S(v),d.trn.a.v(d.trn.a.i(this.c.J(),"PathGeometry"),"Path.Clip must contain PathGeometry"),E=this.u("Figures"),this.hc(E),v=v.vb()),this.c.F()):d.trn.a.i(E,"Path.Data")&&
!this.c.O()?(this.c.G(),this.c.advance()&&(c=new d.trn.D,c.V(this.u("Transform")),null!=v?v.Ka(c):v=c,this.b+=this.S(v),d.trn.a.v(d.trn.a.i(this.c.J(),"PathGeometry"),"Path.Data must contain PathGeometry"),c=this.u("Figures")),this.c.F()):d.trn.a.i(E,"Path.Fill")?(this.c.G(),this.c.advance(),null!=w||b||"ImageBrush"!==this.c.J()||(g=!0,this.b+=this.We()),l=this.bb("c."+d.trn.a.f[d.trn.a.ta],f),this.c.F()):d.trn.a.i(E,"Path.OpacityMask")?this.da||(this.c.G(),this.c.advance(),w=this.bb("c."+d.trn.a.f[d.trn.a.ta],
f),this.c.F()):d.trn.a.i(E,"Path.Stroke")&&(this.c.G(),this.c.advance(),p=this.bb("c."+d.trn.a.f[d.trn.a.Ub],"c."+d.trn.a.f[d.trn.a.sb]+"();",n),this.c.F())}this.c.F()}if(null==w&&!b&&!g){d.trn.a.v(null!=c,"Paths must have Data defined");g=this.c.w("StrokeDashArray");if(null!=g)for(g=g.split(" "),m=Array(g.length),v=0;v<g.length;++v)if(m[v]=parseFloat(g[v])*n,!m[v]||.02>m[v])m[v]=.02;this.Rd(e?"evenodd":"nonzero");e=this.xa("StrokeDashOffset",0);null!=m&&null!=l&&(this.Nc(c),null!=l&&this.ic(l,f),
l=null);this.Pd(c,m,e);null!=l&&this.ic(l,f);null!=p&&(this.sf(this.Xe(this.za("StrokeStartLineCap","Flat"))),this.tf(this.za("StrokeLineJoin","miter").toLowerCase()),this.uf(this.xa("StrokeMiterLimit",10)),this.vf(p))}k&&(this.b+=this.va,this.ma());if(null!=w||b)this.da=!0,this.yc(w,a);this.da=!1},ud:function(a){var b=1,c=[255,255,255,255];if("#"===a.charAt(0)){if(7===a.length)return"'"+a+"'";var e,f;d.trn.a.v(9===a.length,"Color "+a+" is invalid in a XOD file");b=a.substr(1,2);e=a.substr(3,2);f=
a.substr(5,2);a=a.substr(7,2);b=parseInt(b,16)/255;c[0]=parseInt(e,16);c[1]=parseInt(f,16);c[2]=parseInt(a,16)}else"s"===a.charAt(0)?(e=a.split("#")[1].split(","),3<e.length?(b=parseFloat(e[0]),f=255*parseFloat(e[1]),c[0]=parseInt(0>f?0:255<f?255:f),f=255*parseFloat(e[2]),c[1]=parseInt(0>f?0:255<f?255:f),f=255*parseFloat(e[3])):(f=255*parseFloat(e[0]),c[0]=parseInt(0>f?0:255<f?255:f),f=255*parseFloat(e[1]),c[1]=parseInt(0>f?0:255<f?255:f),f=255*parseFloat(e[2])),c[2]=parseInt(0>f?0:255<f?255:f)):
d.trn.a.v(!1,"Invalid color for a XOD file");return"'rgba("+c[0]+","+c[1]+","+c[2]+","+d.trn.a.l(b)+")'"},Bd:function(a,b){return this.Zb(this.u("Color"),a,b)},Zb:function(a,b,c){return b+"="+this.ud(a)+";"+c},$b:function(a){return this.Dd("var "+a+"=function(c)")},Dd:function(a){var b=this.Sa,c=this.b;this.b="";this.Sa=this.c.depth;this.T(!0);this.b+=a+"{";if(!this.c.O()||!d.trn.a.i(this.c.J(),"Canvas"))for(this.Oa=!1;this.Jc(););this.ma();this.b+="};";this.Sa=b;a=this.b;this.b=c;return a},Cd:function(a,
b,c,e){var f="",g=this.u("Viewbox"),k=new d.trn.ba;k.Va(g);var g=this.u("Viewport"),l=new d.trn.ba;l.Va(g);g=this.c.w("Transform");f+=this.$;this.T();var m;if(!this.c.O()){for(this.c.G();this.c.advance();){var n=this.c.J();d.trn.a.i(n,"VisualBrush.Visual")&&(this.c.G(),d.trn.a.v(this.c.advance(),"VisualBrush.Visual must contain Canvas, Path or Glyphs element"),this.T(!0),N(this.K).ua=new d.trn.D,m=this.Wb(),this.ma(),this.c.F())}this.c.F()}if("undefined"!==typeof m&&0!==m.A&&0!==m.B){var n=l.o-k.o,
p=l.s-k.s;k.lb(m);l=k;l.o+=n;l.s+=p}if(null!=g||k!==l)n=l.B/k.B,m=l.A/k.A,p=l.o-k.o*n,l=l.s-k.s*m,null!=g&&(this.Na(g)?f+=this.Yb(g):c.V(g)),g=new d.trn.D,g.ub(n,0,0,m,p,l),c.Ka(g),f+=this.S(c);l=Math.min(k.B,k.A);f+="var a=asc(t)*"+d.trn.a.l(this.eb().Kb())+";if(a*"+l+"<2)a=2/"+l+";";if(k.o||k.s)f+="c."+d.trn.a.f[d.trn.a.Vb]+"("+d.trn.a.l(k.o)+","+d.trn.a.l(k.s)+");";f+="c."+d.trn.a.f[d.trn.a.Ac]+"(1/a,1/a);";l=this.xa("Opacity",1);1>l&&(f+=this.$a(l));l=this.za("TileMode","None");++this.Eb;g="c"+
this.Eb;m="x"+this.Eb;f=f+("var "+g+"=document.createElement('canvas');")+(g+".width=")+k.B;f=f+("*a;"+g+".height=")+k.A;f=f+"*a;"+("var "+m+"="+g+".getContext('2d');")+(m+"."+d.trn.a.f[d.trn.a.Ac]+"(a,a);");if(k.o||k.s)f+=m+"."+d.trn.a.f[d.trn.a.Vb]+"("+d.trn.a.l(-k.o)+","+d.trn.a.l(-k.s)+");";-1!==b.indexOf("c."+d.trn.a.f[d.trn.a.sb])&&(f+="c."+d.trn.a.f[d.trn.a.md]+"=a*"+e/c.Kb()+";");c=this.c.w("Visual");c=null!=c?this.vc(c):"v"+this.Eb;if(!this.c.O()){for(this.c.G();this.c.advance();)n=this.c.J(),
d.trn.a.i(n,"VisualBrush.Visual")&&(this.c.G(),d.trn.a.v(this.c.advance(),"VisualBrush.Visual must contain Canvas, Path or Glyphs element"),f+=this.$b(c),this.c.F());this.c.F()}f=f+c+("("+m+");");f+=a;f+="=c."+d.trn.a.f[d.trn.a.kd]+"("+g+",";f="None"===l?f+"'no-repeat'":f+"'repeat'";f+=");";f+=b;f+=this.va;this.ma();return f},Na:function(a){return"{"===a.charAt(0)},vc:function(a){var b=a.indexOf("StaticResource");d.trn.a.v(0<b,"Invalid resource reference: "+a);b+=15;a=a.substr(b,a.length-1-b);for(var b=
null,c=this.la.length-1;0<=c;--c)if(Object.be(this.la[c],a)){b=this.la[c][a];break}d.trn.a.v(null!=b,"Dictionary key "+a+" does not exist.");return b},cb:function(a,b,c){return this.vc(a)+"(c,"+b+",'"+c+"');"},Yb:function(a){return this.vc(a)+"(c);"},Jc:function(){var a;if(this.Oa){if(this.c.depth===this.Sa)return d.trn.a.i(this.c.J(),"Canvas")&&this.Gb(),!1;a=this.c.advance();if(!a){this.c.F();if(N(this.ac)===this.c.depth)return this.ac.pop(),this.Te(),!0;if(this.c.depth===this.Sa)return d.trn.a.i(this.c.J(),
"Canvas")&&this.Gb(),!1;this.Gb();return!0}}this.Oa=!0;a=this.c.J();d.trn.a.i(a,"Canvas")?this.lf():d.trn.a.i(a,"Path")?this.pf():d.trn.a.i(a,"Glyphs")?this.Nd(d.trn.a.f,!1):d.trn.a.i(a,"trn:Glyphs")&&(this.c.O()||this.ac.push(this.c.depth),this.Nd(d.trn.a.jf,!0),this.c.O()||(this.c.G(),this.wf()));return!0},Xb:function(){var a=this.Zd(),b="r"+this.Cb.toString();++this.Cb;return this.la[this.la.length-1][a]=b},fd:function(){var a=this.Xb();this.b+="var "+a+"=function(c){\n"},pb:function(){var a=this.Zd(),
b="r"+this.Cb.toString();++this.Cb;this.la[this.la.length-1][a]=b;this.b+="var "+b+"=function(c,s,o){"},La:function(){this.b+="};"},bb:function(a,b,c){var e=new d.trn.D,f=this.c.J();d.trn.a.i(f,"VisualBrush")?a=this.Cd(a,b,e,c):(d.trn.a.i(f,"ImageBrush")?a=this.xd(a,b,e):d.trn.a.i(f,"LinearGradientBrush")?a=this.yd(a,b,e):d.trn.a.i(f,"RadialGradientBrush")?a=this.Ad(a,b,e):d.trn.a.i(f,"SolidColorBrush")?a=this.Bd(a,b):(d.trn.a.v(!1,"Invalid Brush Type: "+f),a=""),"undefined"!==typeof c&&this.Sd(c/
e.Kb()));return a},Qd:function(){var a=this.c.J();if(d.trn.a.i(a,"ResourceDictionary")&&!this.c.O()){var b="c[(s?'"+d.trn.a.f[d.trn.a.ta]+"':'"+d.trn.a.f[d.trn.a.Ub]+"')]";for(this.c.G();this.c.advance();)a=this.c.J(),d.trn.a.i(a,"ImageBrush")?(this.pb(),this.b+=this.xd(b,"eval(o);",new d.trn.D),this.La()):d.trn.a.i(a,"LinearGradientBrush")?(this.pb(),this.b+=this.yd(b,"eval(o);",new d.trn.D),this.La()):d.trn.a.i(a,"RadialGradientBrush")?(this.pb(),this.b+=this.Ad(b,"eval(o);",new d.trn.D),this.La()):
d.trn.a.i(a,"VisualBrush")?(this.pb(),this.b+=this.Cd(b,"eval(o);",new d.trn.D),this.La()):d.trn.a.i(a,"SolidColorBrush")?(this.pb(),this.b+=this.Bd(b,"eval(o);"),this.La()):d.trn.a.i(a,"MatrixTransform")?(this.fd(),this.nf(),this.La()):d.trn.a.i(a,"PathGeometry")?(this.fd(),this.Nc(this.u("Figures")),this.La()):d.trn.a.i(a,"Path")?(a=this.Xb(),this.b+=this.$b(a)):d.trn.a.i(a,"Glyphs")?(a=this.Xb(),this.b+=this.$b(a)):d.trn.a.i(a,"Canvas")?(a=this.Xb(),this.b+=this.$b(a)):d.trn.a.v(!1,"Resource type is invalid: "+
a);this.c.F()}},Ve:function(){for(var a="";!this.done;)a+=this.fe();return a},fe:function(){this.b+="var ob=[0,0];";this.Ld=!1;for(this.yb={};this.b.length<this.Gd&&!this.Ld&&this.Jc(););this.Jc()||(this.done=!0);var a=this.b;this.b="";return a},Af:function(){var a=[],b=this.yb,c;for(c in b)a.add(c.substr(1));return a},done:!1,Oa:!1,$:null,va:null,da:!1,b:null,Kd:0,Jd:0,Cb:0,Eb:0,Fc:!1,Ta:0,cf:0,Gd:0,Pa:null,yb:null,Sa:0,la:null,K:null,c:null,ac:null,dc:!1};
d.trn.Ba=function(){this.Ic=this.Db=!1;this.bc=this.Gc=1;this.Ec=this.fc=this.gc=this.ec=0};d.trn.Ba.prototype={Db:!1,Ic:!1,bc:0,Gc:0,ec:0,Ec:0,fc:0,gc:0};d.trn.Ma=function(){};d.trn.Ma.Ff=function(a,b){var c=new d.trn.Ma;c.kb="black";c.gb="black";c.fb="nonzero";c.Qa=1;c.Bb="source-over";c.ib=1;c.hb="butt";c.Ra="miter";c.jb=10;c.Ab="10px sans-serif";c.ua=new d.trn.D;c.na=new d.trn.ba;c.na.Lb(0,0,a,b);return c};
d.trn.Ma.prototype={clone:function(){var a=new d.trn.Ma;a.kb=this.kb;a.gb=this.gb;a.fb=this.fb;a.Qa=this.Qa;a.Bb=this.Bb;a.ib=this.ib;a.hb=this.hb;a.Ra=this.Ra;a.jb=this.jb;a.Ab=this.Ab;a.ua=new d.trn.D;a.ua.Ed(this.ua);a.na=new d.trn.ba;a.na.Lb(this.na.o,this.na.s,this.na.B,this.na.A);return a},If:function(){var a=new d.trn.Ma;a.kb="black";a.gb="black";a.fb="nonzero";a.Qa=1;a.Bb="source-over";a.ib=1;a.hb="butt";a.Ra="miter";a.jb=10;a.Ab="10px sans-serif";a.ua=new d.trn.D;a.ua.Ed(this.ua);a.na=new d.trn.ba;
return a},kb:null,gb:null,fb:null,Qa:0,ib:0,hb:null,Ra:null,jb:0,Ab:null,ua:null,na:null};d.trn.Ya=function(a,b){this.x=a;this.y=b};d.trn.Ya.prototype={x:0,y:0};d.trn.ba=function(){this.s=this.o=-1E6;this.B=this.A=2E6};
d.trn.ba.prototype={Lb:function(a,b,c,e){this.o=a;this.s=b;this.B=c;this.A=e},Hf:function(){return 0<this.B&&0<this.A},Va:function(a){a=a.split(",");d.trn.a.v(4===a.length,"Rectangles should contain 4 numbers");this.o=parseFloat(a[0]);this.s=parseFloat(a[1]);this.B=parseFloat(a[2]);this.A=parseFloat(a[3])},Df:function(a){if(a.Fd())return this;var b=new d.trn.Ya(this.o,this.s),c=new d.trn.Ya(this.o,this.s+this.A),e=new d.trn.Ya(this.o+this.B,this.s),f=new d.trn.Ya(this.o+this.B,this.s+this.A);a.lc(b);
a.lc(c);a.lc(e);a.lc(f);a=Math.min(b.x,c.x,e.x,f.x);var g=Math.min(b.y,c.y,e.y,f.y),k=new d.trn.ba;k.Lb(a,g,Math.max(b.x,c.x,e.x,f.x)-a,Math.max(b.y,c.y,e.y,f.y)-g);return k},fa:function(a,b){a<this.o?(this.B+=this.o-a,this.o=a):a>this.o+this.B&&(this.B=a-this.o);b<this.s?(this.A+=this.s-b,this.s=b):b>this.s+this.A&&(this.A=b-this.s)},Sc:function(a){this.fa(a.o,a.s);this.fa(a.o+a.B,a.s+a.A)},lb:function(a){var b,c,e,f,g,k,l;b=this.o;c=this.o+this.B;e=this.s;f=this.s+this.A;g=a.o;k=a.o+a.B;l=a.s;a=
a.s+a.A;c<g||k<b||f<l||a<e?this.o=this.B=this.s=this.A=0:(this.o=b<g?g:b,this.B=(c<k?c:k)-this.o,this.s=e<l?l:e,this.A=(f<a?f:a)-this.s,this.B&&this.A||(this.o=this.B=this.s=this.A=0))},ae:function(a){this.o-=a;this.s-=a;this.B+=2*a;this.A+=2*a},o:0,s:0,B:0,A:0};d.trn.D=function(){};
d.trn.D.prototype={W:1,X:0,Y:0,Z:1,ca:0,ea:0,V:function(a){var b=[1,0,0,1,0,0];a=a.split(",");for(var c=0;c<a.length&&6>c;++c)b[c]=parseFloat(a[c]);this.W=b[0];this.X=b[1];this.Y=b[2];this.Z=b[3];this.ca=b[4];this.ea=b[5]},ub:function(a,b,c,e,f,g){this.W=a;this.X=b;this.Y=c;this.Z=e;this.ca=f;this.ea=g},Ed:function(a){this.W=a.W;this.X=a.X;this.Y=a.Y;this.Z=a.Z;this.ca=a.ca;this.ea=a.ea},Ka:function(a){var b=this.W,c=this.X,e=this.Y,f=this.Z;this.W=a.W*b+a.X*e;this.X=a.W*c+a.X*f;this.Y=a.Y*b+a.Z*
e;this.Z=a.Y*c+a.Z*f;this.ca=a.ca*b+a.ea*e+this.ca;this.ea=a.ca*c+a.ea*f+this.ea},vb:function(){var a=new d.trn.D,b=this.W*this.Z-this.X*this.Y;if(!b)return a;a.W=this.Z/b;a.Y=-this.Y/b;a.ca=(this.Y*this.ea-this.ca*this.Z)/b;a.X=-this.X/b;a.Z=this.W/b;a.ea=-(this.W*this.ea-this.ca*this.X)/b;return a},lc:function(a){var b=a.x*this.X+a.y*this.Z+this.ea;a.x=a.x*this.W+a.y*this.Y+this.ca;a.y=b},Kb:function(){var a=.707106781*this.W+.707106781*this.X,b=.707106781*this.Y+.707106781*this.Z;return Math.sqrt(a*
a+b*b)},Fd:function(){return 1!==this.W||this.X||this.Y||1!==this.Z||this.ca||this.ea?!1:!0},tb:function(){return this.zd("c")},zd:function(a){return this.Fd()?"":a+"."+d.trn.a.f[d.trn.a.qd]+"("+d.trn.a.Ib(this.W,4)+","+d.trn.a.Ib(this.X,4)+","+d.trn.a.Ib(this.Y,4)+","+d.trn.a.Ib(this.Z,4)+","+d.trn.a.l(this.ca)+","+d.trn.a.l(this.ea)+");"}};
d.trn.Tb=function(a,b,c,e){this.C=a;this.m=b;this.g=this.h=0;this.N=!1;this.oa=c;if(null!=this.oa){for(b=a=0;b<this.oa.length;++b)a+=this.oa[b];this.Da=e%a;0>this.Da&&(this.Da+=a);for(b=this.Hc=0;this.Da>this.oa[b];++b)this.Da-=this.oa[b],++this.Hc}};d.trn.Tb.prototype={C:null,m:0,oa:null,cc:0,zb:0,Hc:0,Da:0,g:0,h:0,Hd:0,Id:0,N:!1,ja:0,ka:0};d.trn.Md=function(a,b,c){this.ef=a;this.ff=b;this.df=c};d.trn.Md.prototype={df:0,ff:0,ef:0};d.trn.a.U("myglobs.trn.Converter");d.trn.Ba.U("myglobs.trn._index");
d.trn.Ma.U("myglobs.trn._gState");d.trn.Ya.U("myglobs.trn.Point");d.trn.ba.U("myglobs.trn._rect");d.trn.D.U("myglobs.trn._matrix2D");d.trn.Tb.U("myglobs.trn._abbrGeomItr");d.trn.Md.U("myglobs.trn._pageInfo");d.trn.a.fg="http://schemas.microsoft.com/xps/2005/06/resourcedictionary-key";d.trn.a.jg="http://schemas.openxps.org/oxps/v1.0/resourcedictionary-key";d.trn.a.pg="http://schemas.microsoft.com/winfx/2006/xaml";d.trn.a.xf="http://schemas.microsoft.com/xps/2005/06";d.trn.a.qg="http://schemas.microsoft.com/winfx/2006/xaml/presentation";
d.trn.a.kg="http://schemas.openxps.org/oxps/v1.0";d.trn.a.sg="http://schemas.microsoft.com/xps/2005/06/documentstructure";d.trn.a.ig="http://schemas.openxps.org/oxps/v1.0/documentstructure";d.trn.a.ng="http://schemas.openxmlformats.org/package/2006/relationships";d.trn.a.Zf="http://schemas.openxmlformats.org/package/2006/content-types";d.trn.a.gg="http://schemas.openxmlformats.org/markup-compatibility/2006";d.trn.a.$f="http://schemas.openxmlformats.org/package/2006/metadata/core-properties";
d.trn.a.ag="http://purl.org/dc/elements/1.1/";d.trn.a.bg="http://purl.org/dc/terms/";d.trn.a.rg="http://www.w3.org/XML/1998/namespace";d.trn.a.og="clr-namespace:PDFTron.SilverDox.Internal;assembly=SilverDox";d.trn.a.tg="http://schemas.microsoft.com/xps/2005/06/restricted-font";d.trn.a.lg="http://schemas.openxps.org/oxps/v1.0/restricted-font";d.trn.a.hg="application/vnd.ms-package.obfuscated-opentype";d.trn.a.mg="http://www.pdftron.com/silverdox/2010/09";d.trn.a.Re=0;d.trn.a.Qe=1;d.trn.a.qd=2;
d.trn.a.Vb=3;d.trn.a.md=4;d.trn.a.Me=5;d.trn.a.Ub=6;d.trn.a.ta=7;d.trn.a.Le=8;d.trn.a.Ee=9;d.trn.a.Fe=10;d.trn.a.kd=11;d.trn.a.Ae=12;d.trn.a.hd=13;d.trn.a.jd=14;d.trn.a.ab=15;d.trn.a.sb=16;d.trn.a.De=17;d.trn.a.zc=18;d.trn.a.rb=19;d.trn.a.Pe=20;d.trn.a.Be=21;d.trn.a.Ke=22;d.trn.a.Ie=23;d.trn.a.nd=24;d.trn.a.Se=25;d.trn.a.Oe=26;d.trn.a.Ne=27;d.trn.a.qb=28;d.trn.a.od=29;d.trn.a.cg=30;d.trn.a.dg=31;d.trn.a.Ac=32;d.trn.a.Je=33;d.trn.a.Ge=34;d.trn.a.He=35;d.trn.a.ld=36;d.trn.a.Ce=37;d.trn.a.pd=38;
d.trn.a.f="S r t T w c s f a L R P A b z F X C M l q B n x m W i j I Z d D e xw cgb cge g bO tm".split(" ");d.trn.a.jf="S r t T w c s f a L R P A b z F X C M l q B n xc m W i j I Z d D e xcw cgb cge g bO tm".split(" ");self.trn.a||(self.trn=trn);function V(a){this.H="";this.Of=new self.Za.sc(a);W(this);this.start=0}V.prototype={Ud:102400,mark:function(a){var b=a-this.start;b>V.prototype.Ud&&(this.H=this.H.slice(b),this.start=a)},indexOf:function(a,b){var c;b-=this.start;do c=this.H.indexOf(a,b);while(-1===c&&W(this));return c+this.start},charAt:function(a){a-=this.start;a>=this.H.length&&W(this);return this.H.charAt(a)},substring:function(a,b){a-=this.start;b-=this.start;return this.H.substring(a,b)}};
function W(a){var b=a.Of.Yd(V.prototype.Ud);return b.length?(a.H+=b,!0):!1}self.qe=V;self.Td=!1;
self.onmessage=function(a){switch(a.data.command){case "data":a=new self.te(new self.qe(a.data.dataString));self.Hb=new self.trn.a(a,self.Td,self.Mf);break;case "nextChunk":self.Hb.done?(self.postMessage({command:"done"}),self.Hb=null):(a=self.Hb.fe(),self.postMessage({command:"nextChunk",resources:self.Hb.Af(),dataString:a}));break;case "cancel":self.Hb=null;self.postMessage({command:"done"});break;case "options":self.Td=a.data.imageScaling;self.Mf=a.data.specialBlendSupported;break;default:throw Error("Unknown message command "+
a.data.command);}};
